# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

# ---- llm ----
model: llama-server:gpt-oss



# ---- behavior ----
stream: true                     # Controls whether to use the stream-style API.
save: true                       # Indicates whether to persist the message
editor: micro                    # Specifies the command used to edit input buffer or session. (e.g. vim, emacs, nano).
wrap: 80                         # Controls text wrapping (no, auto, <max-width>)
wrap_code: true                  # Enables or disables wrapping of code blocks



# ---- function-calling ----
# Visit https://github.com/sigoden/llm-functions for setup instructions
function_calling: true           # Enables or disables function calling (Globally).
mapping_tools:                   # Alias for a tool or toolset
  fs: 'fs_cat,fs_ls,fs_mkdir,fs_rm,fs_write'
use_tools: fs,web_search.        # Which tools to use by default. (e.g. 'fs,web_search')



# ---- prelude ----
repl_prelude: null    # Set a default role or session for REPL mode (e.g. role:<name>, session:<name>, <session>:<role>)
cmd_prelude: null.    # Set a default role or session for CMD mode (e.g. role:<name>, session:<name>, <session>:<role>)
agent_prelude: null.  # Set a session to use when starting a agent (e.g. temp, default)



# ---- session ----
save_session: true
compress_threshold: 4000
summarize_prompt: 'Fasse die bisherige Konversation kurz in 200 Wörtern oder weniger zusammen, um sie als Vorlage für den zukünftigen Kontext zu verwenden.'
summary_prompt: 'Dies ist eine Zusammenfassung des Chatverlaufs als Zusammenfassung: '



# ---- apperence ----
highlight: true       # Controls syntax highlighting
light_theme: false
# Custom REPL left/right prompts, see https://github.com/sigoden/aichat/wiki/Custom-REPL-Prompt for more details
left_prompt:
  '{color.green}{?session {?agent {agent}>}{session}{?role /}}{!session {?agent {agent}>}}{role}{?rag @{rag}}{color.cyan}{?session )}{!session >}{color.reset} '
right_prompt:
  '{color.purple}{?session {?consume_tokens {consume_tokens}({consume_percent}%)}{!consume_tokens {consume_tokens}}}{color.reset}'



clients:
- type: openai-compatible
  name: llama-server
  api_base: http://localhost:8315/v1
  models:
  - name: gpt-oss
    supports_function_calling: true

  - name: qwen-next
    supports_function_calling: true
  
  - name: glm-air
    supports_function_calling: true
