

# ——— sudos ———————————————————————————
alias nala='sudo nala'
alias pkgs='sudo pkgin'
alias suse='sudo zypper'
alias suzy='sudo zypper'
alias ssapk='doas apk'
alias ssapt='sudo apt'
alias ssbtr='sudo btrfs'
alias sscat='sudo cat'
alias  sscp='sudo cp --preserve=all'
alias ssctl='sudo systemctl'
alias  sctl='sudo systemctl'
alias ssdnf='sudo dnf'
alias   ssi='sudo -i'
alias sskll='sudo kill -9'
alias smic='sudo micro'
alias ssmod='sudo chmod'
alias ssmnt='sudo mount'
alias  ssmv='sudo mv'
alias ssnal='sudo nala'
alias ssown='sudo chown'
alias  ssrm='sudo rm'
alias ssrpm='sudo rpm'
alias ssuzy='sudo zypper'
alias  suzy='sudo zypper'
alias ssvim='sudo vim'
alias  svim='sudo vim'
